spring:
  datasource:
    url: jdbc:postgresql://ep-silent-block-a57tem1m.us-east-2.aws.neon.tech/dc_portal
    username: mladmin_owner
    password: itqaj5e6HwLE
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or validate, create, create-drop based on your needs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis-10255.c322.us-east-1-2.ec2.redns.redis-cloud.com
      port: 10255
      username: default
      password: k7Nz0S8c4mUT9LjTmUDq0EqyVrVKl70o 
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    com.dc.portal.security: DEBUG
    graphql.schema.idl: DEBUG
    graphql.GraphQL: DEBUG
    com.dc.portal: DEBUG
  
jwt:
  secret: empover
  expiration: 86400000  # 24 hours
  
management:
  endpoints:
    web:
      exposure:
        include: health
